#!/bin/bash

set -ue

clear

git status

python setup.py check -mrs

echo
echo "this will update version from $(head -n 1 VERSION) to $VERSION"
echo
read -p "are you sure you wish to publish? [y/N] " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # activate virtualenv
    set +u
    source venv/bin/activate
    set -u

    set -v

    # convert README to plain text (pypi doesn't supprt markdown)
    pandoc --from=markdown --to=plain README.md -o README

    # update and add version, tag it, and push it
    git stash
    echo "$VERSION" > VERSION
    git add VERSION
    git commit -m "Updated version to $VERSION"
    git tag "$VERSION"
    git push --tags origin master
    git stash pop

    # upload to pypi
    python3 setup.py sdist upload -r pypi

    rm -f README
else
    echo "aborting..."
    exit 1
fi
