#!/bin/bash

set -ue

clear
git status
echo
read -p "Are you sure you wish to publish version=$VERSION? [y/N] " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    # activate virtualenv
    set +u
    source venv/bin/activate
    set -u

    set -v

    # update and add version, tag it, and push it
    echo "$VERSION" > VERSION
    git add VERSION
    git commit -m "Updated version to $VERSION"
    git tag "$VERSION"
    git push --tags origin master

    # convert README to reStructuredText (pypi doesn't supprt markdown)
    pandoc --from=markdown --to=rst README.md -o README

    # upload to pypi
    python3 setup.py sdist upload -r pypi

    rm -f README
else
    echo "aborting..."
fi

