#!/bin/bash

set -ue

function clean() {
    rm -f README
}
trap clean EXIT

git status
git diff-index --quiet HEAD --

echo
echo "this will update version from $(head -n 1 VERSION) to $VERSION"
echo
read -p "are you sure you wish to publish? [y/N] " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 'For readme see `GitHub <https://github.com/PolarPayne/ppgr>`_.' > README

    # update and add version, tag it, and push it
    echo "$VERSION" > VERSION
    git add VERSION
    git commit -m "Updated version to $VERSION"
    git tag "$VERSION"
    git push --tags origin master

    # upload to pypi
    pipenv run -- python3 setup.py sdist upload
else
    echo "aborting..."
    exit 1
fi
